version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 35
    groups:
      prod:
        dependency-type: production
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
      dev:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci(deps): "
  - package-ecosystem: pip
    directory: /deployer
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: pip
    directory: /testing/integration
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: npm
    directory: /client/pwa
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      prod:
        dependency-type: production
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
      dev:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
  - package-ecosystem: npm
    directory: /cloud-function
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      prod:
        dependency-type: production
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
      dev:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
  - package-ecosystem: npm
    directory: /libs/locale-utils
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      prod:
        dependency-type: production
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
      dev:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
  - package-ecosystem: npm
    directory: /libs/pong
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      prod:
        dependency-type: production
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
      dev:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
  - package-ecosystem: npm
    directory: /libs/slug-utils
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      prod:
        dependency-type: production
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
      dev:
        dependency-type: development
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@mdn/*"
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
