version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 35
    ignore:
      # Temporarily disable updates to Dinocons
      - dependency-name: "@mdn/dinocons"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directory: "/deployer"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/testing/integration"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "/client/pwa"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/lib/slug-utils"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/deployer/aws-lambda/mdn-stripe-price-ids"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/deployer/aws-lambda/content-origin-request"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/deployer/aws-lambda/content-origin-response"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/deployer/aws-lambda/tests"
    schedule:
      interval: daily
    open-pull-requests-limit: 10

    # This forces the Dependabot commit messages to conform to something
    # our auto-merge workflow can always cope with.
    # See https://github.com/ahmadnassri/action-dependabot-auto-merge/issues/31#issuecomment-718779806
    commit-message:
      prefix: build
      prefix-development: chore
      include: scope
