export const ARTICLE_ACTIONS_COLLECTION_SELECT_OPENED =
  "ARTICLE_ACTIONS_COLLECTION_SELECT_OPENED";
export const ARTICLE_ACTIONS_NEW_COLLECTION = "ARTICLE_ACTIONS_NEW_COLLECTION";
export const ARTICLE_ACTIONS_OPENED = "ARTICLE_ACTIONS_OPENED";
export const BANNER_PREVIEW_FEATURES_DISMISSED =
  "BANNER_PREVIEW_FEATURES_DISMISSED";
export const BANNER_PREVIEW_FEATURES_SETTINGS_LINK =
  "BANNER_PREVIEW_FEATURES_SETTINGS_LINK";
export const COLLECTIONS_BANNER_NEW_COLLECTION =
  "COLLECTIONS_BANNER_NEW_COLLECTION";
export const NEW_COLLECTION_MODEL_SUBMIT_ARTICLE_ACTIONS =
  "NEW_COLLECTION_MODEL_SUBMIT_ARTICLE_ACTIONS";
export const NEW_COLLECTION_MODEL_SUBMIT_COLLECTIONS_PAGE =
  "NEW_COLLECTION_MODEL_SUBMIT_COLLECTIONS_PAGE";
export const TOGGLE_PLUS_OFFLINE_DISABLED = "TOGGLE_PLUS_OFFLINE_DISABLED";
export const TOGGLE_PLUS_OFFLINE_ENABLED = "TOGGLE_PLUS_OFFLINE_ENABLED";
