name: "Mark new issues with needs-triage label"
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label-new-issues:
    uses: mdn/workflows/.github/workflows/new-issues.yml@main
    with:
      target-repo: "mdn/yari"
